### ISSUE TITLE
Auto complete clears input

### ISSUE THREAD

**Issue by hughleat** [darkfrog26/hyperscala#23] opened 2015-03-20 15:19 UTC
Hi,

Not 100% sure if this is an error, or if I'm just doing it incorrectly.  I have the following page:

    class TestPage extends Webpage( Finance ) {
        this.require( Autocomplete )
        body.contents += new Autocomplete {
            autocomplete.search := (
                ( query : String ) => Seq( "aaa", "aab" ).map( s => AutocompleteResult( s, s ))
            )
        }
    }

If I type "a" in the input, the right options come up.  If I select one the input is filled in.  But if I click anywhere on the page the input is cleared.

The same thing happens on the examples site: http://www.hyperscala.org/example/ui/autocomplete.html

If this is expected behaviour, how do I get it to stay put?

Cheers,

Hugh.

**Comment by darkfrog26** [comment] 2015-03-20 15:26
This is expected behavior, but perhaps it shouldn't be.  The reason this happens is because when the field loses focus the visual representation is updated to reflect the currently selected element.  In this case because you haven't typed in anything that matches properly to a option and you haven't selected one, it reverts to null which is represented by default as an empty field.

How would you want this to work differently?

**Comment by hughleat** [comment] 2015-03-20 15:34
Ah, sorry about that.  

So what I was looking for was an input box which could auto complete suggestions but would also allow me to enter new text, too.

BTW, if I click on the "aaa" from the suggestions, it still goes away if I click elsewhere afterwards.
If I then type "a" in the box and click away, it then puts "null" in the box.
If after that I type "a" in the box and click away, it leaves the "a" in the box.

**Comment by darkfrog26** [comment] 2015-03-20 16:20
You are correct, there are some serious issues with that component.  You might want to consider http://hyperscala.org/example/ux/singleselectlist.html instead.  It's far more flexible both in style and function.  I'll try to get a look at Autocomplete in the near future though.

**Comment by hughleat** [comment] 2015-03-20 16:34
Thanks for the amazing quick responses :-)

**Comment by darkfrog26** [comment] 2015-03-20 16:45
I don't promote Hyperscala much, but I use it for many of my clients, so I'm constantly working on it.

BTW, how did you come across Hyperscala?

**Comment by hughleat** [comment] 2015-03-20 16:48
I can't remember where I found it originally.  I first saw it years ago, waiting for a chance to play (I'm a compiler guy so building web stuff is miles off my list).

IMO, you have exactly the right design methodology.  None of the others make sense :-)

**Comment by darkfrog26** [comment] 2015-03-20 16:51
It's funny, I've created several web frameworks over the years (http://www.jseamless.org is my previous iteration), but the reason behind it is because I hate web development. It's ironic how much more time I've actually spent doing web development to try to avoid doing web development.

I appreciate the kind words. The goal of Hyperscala is to be clean and focused on Scala development, not some crazy new language you have to learn.  Feel free to offer any pull requests if you have anything additional to offer. Hyperscala is coming along pretty well, but I'm only one person and can always use more help. :)

**Comment by hughleat** [comment] 2015-03-20 19:09
I would love to.  Gonna take me a while to get into it though - just started looking this morning and an afternoon a year ago.

I do the same thing.  I often spend a month getting a computer to do something automatically that I could probably do manually in 5 minutes :-)

BTW, are you likely to do an integration or release build to maven in the near future?

**Comment by darkfrog26** [comment] 2015-03-20 19:23
Yes, I'm wrapping up my FabricJS wrapper and then I'll be doing the 0.10.0 release...if you're running off a previous release I would recommend either updating to the snapshot or building locally as it's a pretty major change.

**Comment by darkfrog26** [comment] 2015-03-26 18:06
This has been fixed with the latest commit. Take a look at the updated example to see how it should be utilized: https://github.com/darkfrog26/hyperscala/blob/master/examples/src/main/scala/org/hyperscala/examples/ui/AutoCompleteExample.scala

**Closed by darkfrog26** 2015-03-26 18:06 UTC

**Comment by hughleat** [comment] 2015-03-29 14:07
Thanks Matt!
